# Generated by Django 2.1.3 on 2020-11-21 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
